//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsConnectivityState {
  XCS_Disconnected,
  XCS_Rejected,
  XCS_PluggedIn,
  XCS_Wireless,
  XCS_File,
  XCS_Unknown
}

}
