//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsDeviceModePS : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsDeviceModePS(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsDeviceModePS obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsDeviceModePS() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsDeviceModePS(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsOutputMode m_outputMode {
    set {
      xsensdeviceapiPINVOKE.XsDeviceModePS_m_outputMode_set(swigCPtr, (int)value);
    } 
    get {
      XsOutputMode ret = (XsOutputMode)xsensdeviceapiPINVOKE.XsDeviceModePS_m_outputMode_get(swigCPtr);
      return ret;
    } 
  }

  public XsOutputSettings m_outputSettings {
    set {
      xsensdeviceapiPINVOKE.XsDeviceModePS_m_outputSettings_set(swigCPtr, (int)value);
    } 
    get {
      XsOutputSettings ret = (XsOutputSettings)xsensdeviceapiPINVOKE.XsDeviceModePS_m_outputSettings_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_period {
    set {
      xsensdeviceapiPINVOKE.XsDeviceModePS_m_period_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsDeviceModePS_m_period_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_skip {
    set {
      xsensdeviceapiPINVOKE.XsDeviceModePS_m_skip_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsDeviceModePS_m_skip_get(swigCPtr);
      return ret;
    } 
  }

  public XsDeviceModePS(XsOutputMode mode, XsOutputSettings settings, ushort period, ushort skip) : this(xsensdeviceapiPINVOKE.new_XsDeviceModePS__SWIG_0((int)mode, (int)settings, period, skip), true) {
  }

  public XsDeviceModePS(XsOutputMode mode, XsOutputSettings settings, ushort period) : this(xsensdeviceapiPINVOKE.new_XsDeviceModePS__SWIG_1((int)mode, (int)settings, period), true) {
  }

  public XsDeviceModePS(XsOutputMode mode, XsOutputSettings settings) : this(xsensdeviceapiPINVOKE.new_XsDeviceModePS__SWIG_2((int)mode, (int)settings), true) {
  }

  public XsDeviceModePS(XsOutputMode mode) : this(xsensdeviceapiPINVOKE.new_XsDeviceModePS__SWIG_3((int)mode), true) {
  }

  public XsDeviceModePS() : this(xsensdeviceapiPINVOKE.new_XsDeviceModePS__SWIG_4(), true) {
  }

  public int updateRate() {
    int ret = xsensdeviceapiPINVOKE.XsDeviceModePS_updateRate(swigCPtr);
    return ret;
  }

  public void setUpdateRate(int rate) {
    xsensdeviceapiPINVOKE.XsDeviceModePS_setUpdateRate(swigCPtr, rate);
  }

}

}
