//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsDeviceErrorType {
  XERR_Unknown = 0,
  XERR_ImcuTimeout = 1,
  XERR_ImcuSettingsInvalid = 2,
  XERR_ImcuSettingsFailure = 3,
  XERR_ImcuEmtsWriteFailure = 4,
  XERR_ImcuEmtsReadFailure = 5,
  XERR_DspCrashed = 6,
  XERR_DspBootingTimeout = 7,
  XERR_DspSettingsInvalid = 8
}

}
