//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsErrorMode {
  XEM_Ignore = 0x0000,
  XEM_IncreasePacketCounter = 0x0001,
  XEM_IncreasePacketCounterAndSendError = 0x0002,
  XEM_SendErrorAndGoToConfig = 0x0003,
  XEM_Invalid
}

}
