//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsException : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsException(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsException obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsException() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsException(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsException(XsException e) : this(xsensdeviceapiPINVOKE.new_XsException__SWIG_0(XsException.getCPtr(e)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsException(XsResultValue err, XsString description, bool prefix) : this(xsensdeviceapiPINVOKE.new_XsException__SWIG_1((int)err, XsString.getCPtr(description), prefix), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsException(XsResultValue err, XsString description) : this(xsensdeviceapiPINVOKE.new_XsException__SWIG_2((int)err, XsString.getCPtr(description)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsException(XsString description) : this(xsensdeviceapiPINVOKE.new_XsException__SWIG_3(XsString.getCPtr(description)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsResultValue code() {
    XsResultValue ret = (XsResultValue)xsensdeviceapiPINVOKE.XsException_code(swigCPtr);
    return ret;
  }

  public string what() {
    string ret = xsensdeviceapiPINVOKE.XsException_what(swigCPtr);
    return ret;
  }

  public XsString text() {
    XsString ret = new XsString(xsensdeviceapiPINVOKE.XsException_text(swigCPtr), false);
    return ret;
  }

}

}
