//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsFilterProfile : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsFilterProfile(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsFilterProfile obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsFilterProfile() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsFilterProfile(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsFilterProfile(byte type_, byte version_, string label_, char filterType_, byte filterMajor_, byte filterMinor_) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_0(type_, version_, label_, filterType_, filterMajor_, filterMinor_), true) {
  }

  public XsFilterProfile(byte type_, byte version_, string label_, char filterType_, byte filterMajor_) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_1(type_, version_, label_, filterType_, filterMajor_), true) {
  }

  public XsFilterProfile(byte type_, byte version_, string label_, char filterType_) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_2(type_, version_, label_, filterType_), true) {
  }

  public XsFilterProfile(byte type_, byte version_, string label_) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_3(type_, version_, label_), true) {
  }

  public XsFilterProfile(byte type_, byte version_) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_4(type_, version_), true) {
  }

  public XsFilterProfile(byte type_) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_5(type_), true) {
  }

  public XsFilterProfile() : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_6(), true) {
  }

  public XsFilterProfile(XsFilterProfile other) : this(xsensdeviceapiPINVOKE.new_XsFilterProfile__SWIG_7(XsFilterProfile.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = xsensdeviceapiPINVOKE.XsFilterProfile_empty(swigCPtr);
    return ret;
  }

  public XsString toXsString() {
    XsString ret = new XsString(xsensdeviceapiPINVOKE.XsFilterProfile_toXsString(swigCPtr), true);
    return ret;
  }

  public byte type() {
    byte ret = xsensdeviceapiPINVOKE.XsFilterProfile_type(swigCPtr);
    return ret;
  }

  public byte version() {
    byte ret = xsensdeviceapiPINVOKE.XsFilterProfile_version(swigCPtr);
    return ret;
  }

  public string label() {
    string ret = xsensdeviceapiPINVOKE.XsFilterProfile_label(swigCPtr);
    return ret;
  }

  public byte filterType() {
    byte ret = xsensdeviceapiPINVOKE.XsFilterProfile_filterType(swigCPtr);
    return ret;
  }

  public byte filterMajor() {
    byte ret = xsensdeviceapiPINVOKE.XsFilterProfile_filterMajor(swigCPtr);
    return ret;
  }

  public byte filterMinor() {
    byte ret = xsensdeviceapiPINVOKE.XsFilterProfile_filterMinor(swigCPtr);
    return ret;
  }

  public void setType(byte type_) {
    xsensdeviceapiPINVOKE.XsFilterProfile_setType(swigCPtr, type_);
  }

  public void setVersion(byte version_) {
    xsensdeviceapiPINVOKE.XsFilterProfile_setVersion(swigCPtr, version_);
  }

  public void setLabel(string label_) {
    xsensdeviceapiPINVOKE.XsFilterProfile_setLabel(swigCPtr, label_);
  }

  public void setFilterType(char filterType_) {
    xsensdeviceapiPINVOKE.XsFilterProfile_setFilterType(swigCPtr, filterType_);
  }

  public void setFilterVersion(byte major_, byte minor_) {
    xsensdeviceapiPINVOKE.XsFilterProfile_setFilterVersion(swigCPtr, major_, minor_);
  }

  public void swap(XsFilterProfile other) {
    xsensdeviceapiPINVOKE.XsFilterProfile_swap(swigCPtr, XsFilterProfile.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
