//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsProcessingFlag {
  XPF_EnableInitialGyroBiasUpdate = 0x0001,
  XPF_FixedGravity = 0x0002
}

}
