//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsPressure : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsPressure(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsPressure obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsPressure() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsPressure(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsPressure(double pressure, byte age) : this(xsensdeviceapiPINVOKE.new_XsPressure__SWIG_0(pressure, age), true) {
  }

  public XsPressure(double pressure) : this(xsensdeviceapiPINVOKE.new_XsPressure__SWIG_1(pressure), true) {
  }

  public XsPressure() : this(xsensdeviceapiPINVOKE.new_XsPressure__SWIG_2(), true) {
  }

  public XsPressure(XsPressure other) : this(xsensdeviceapiPINVOKE.new_XsPressure__SWIG_3(XsPressure.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public double m_pressure {
    set {
      xsensdeviceapiPINVOKE.XsPressure_m_pressure_set(swigCPtr, value);
    } 
    get {
      double ret = xsensdeviceapiPINVOKE.XsPressure_m_pressure_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_pressureAge {
    set {
      xsensdeviceapiPINVOKE.XsPressure_m_pressureAge_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsPressure_m_pressureAge_get(swigCPtr);
      return ret;
    } 
  }

}

}
