//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsStatusFlagOffset {
  XSFO_OffsetSelfTestOk = 0,
  XSFO_OffsetOrientationValid = 1,
  XSFO_OffsetGpsValid = 2,
  XSFO_OffsetNoRotation = 3,
  XSFO_OffsetClipAccX = 8,
  XSFO_OffsetClipAccY = 9,
  XSFO_OffsetClipAccZ = 10,
  XSFO_OffsetClipGyrX = 11,
  XSFO_OffsetClipGyrY = 12,
  XSFO_OffsetClipGyrZ = 13,
  XSFO_OffsetClipMagX = 14,
  XSFO_OffsetClipMagY = 15,
  XSFO_OffsetClipMagZ = 16,
  XSFO_Retransmitted = 19,
  XSFO_Interpolated = 20,
  XSFO_SyncIn = 21,
  XSFO_SyncOut = 22,
  XSFO_FilterMode = 23,
  XSFO_FilterModeNrOfBits = 3
}

}
