//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsAtomicInt : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsAtomicInt(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsAtomicInt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsAtomicInt() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsAtomicInt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public long m_value {
    set {
      xsensdeviceapiPINVOKE.XsAtomicInt_m_value_set(swigCPtr, value);
    } 
    get {
      long ret = xsensdeviceapiPINVOKE.XsAtomicInt_m_value_get(swigCPtr);
      return ret;
    } 
  }

  public XsAtomicInt(long val) : this(xsensdeviceapiPINVOKE.new_XsAtomicInt__SWIG_0(val), true) {
  }

  public XsAtomicInt() : this(xsensdeviceapiPINVOKE.new_XsAtomicInt__SWIG_1(), true) {
  }

  public void setValue(long val) {
    xsensdeviceapiPINVOKE.XsAtomicInt_setValue(swigCPtr, val);
  }

  public long value() {
    long ret = xsensdeviceapiPINVOKE.XsAtomicInt_value(swigCPtr);
    return ret;
  }

}

}
