//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsDataFlags {
  XSDF_None = 0,
  XSDF_Managed = 1,
  XSDF_FixedSize = 2,
  XSDF_Empty = 4
}

}
