//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsDeviceOptionFlag : uint {
  XDOF_DisableAutoStore = 0x00000001,
  XDOF_DisableAutoMeasurement = 0x00000002,
  XDOF_EnableGpsBeidou = 0x00000004,
  XDOF_DisableGps = 0x00000008,
  XDOF_EnableMagAidedVru = 0x00000010,
  XDOF_None = 0x00000000,
  XDOF_All = 0xFFFFFFFF
}

}
