//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsMtDeviceConfiguration : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsMtDeviceConfiguration(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsMtDeviceConfiguration obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsMtDeviceConfiguration() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsMtDeviceConfiguration(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint m_deviceId {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_deviceId_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_deviceId_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_dataLength {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_dataLength_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_dataLength_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_outputMode {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_outputMode_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_outputMode_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_outputSettings {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_outputSettings_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_outputSettings_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_filterProfile {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterProfile_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterProfile_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_fwRevMajor {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_fwRevMajor_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_fwRevMajor_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_fwRevMinor {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_fwRevMinor_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_fwRevMinor_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_fwRevRevision {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_fwRevRevision_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_fwRevRevision_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_filterType {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterType_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterType_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_filterMajor {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterMajor_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterMajor_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_filterMinor {
    set {
      xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterMinor_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsMtDeviceConfiguration_m_filterMinor_get(swigCPtr);
      return ret;
    } 
  }

  public XsMtDeviceConfiguration() : this(xsensdeviceapiPINVOKE.new_XsMtDeviceConfiguration(), true) {
  }

}

}
