//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsPortInfoArray : XsPortInfoArrayImpl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal XsPortInfoArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsPortInfoArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsPortInfoArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsPortInfoArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsPortInfoArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsPortInfoArray(uint sz, XsPortInfo src) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_0(sz, XsPortInfo.getCPtr(src)), true) {
  }

  public XsPortInfoArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_1(sz), true) {
  }

  public XsPortInfoArray() : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_2(), true) {
  }

  public XsPortInfoArray(XsPortInfoArray other) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_3(XsPortInfoArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsPortInfoArray(XsPortInfo arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_4(XsPortInfo.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsPortInfoArray(XsPortInfo arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_5(XsPortInfo.getCPtr(arg0), sz), true) {
  }

}

}
