//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsSatInfoFlags {
  XSIF_SignalQualityIndicator_Mask = 0x7,
  XSIF_SignalQualityIndicator_NoSignal = 0x0,
  XSIF_SignalQualityIndicator_Searching = 0x1,
  XSIF_SignalQualityIndicator_Acquired = 0x2,
  XSIF_SignalQualityIndicator_Unusable = 0x3,
  XSIF_SignalQualityIndicator_CodeTimeOk = 0x4,
  XSIF_SignalQualityIndicator_CodeCarrierTimeOk1 = 0x5,
  XSIF_SignalQualityIndicator_CodeCarrierTimeOk2 = 0x6,
  XSIF_SignalQualityIndicator_CodeCarrierTimeOk3 = 0x7,
  XSIF_UsedForNavigation_Mask = 0x8,
  XSIF_UsedForNavigation_Used = 0x8,
  XSIF_HealthFlag_Mask = 0x30,
  XSIF_HealthFlag_Unknown = 0x00,
  XSIF_HealthFlag_Healthy = 0x10,
  XSIF_HealthFlag_Unhealthy = 0x20,
  XSIF_Differential_Mask = 0x40,
  XSIF_Differential_Available = 0x40
}

}
