//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsSvInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsSvInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsSvInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsSvInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsSvInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public byte m_chn {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_chn_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsSvInfo_m_chn_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_svid {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_svid_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsSvInfo_m_svid_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_flags {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_flags_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsSvInfo_m_flags_get(swigCPtr);
      return ret;
    } 
  }

  public sbyte m_qi {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_qi_set(swigCPtr, value);
    } 
    get {
      sbyte ret = xsensdeviceapiPINVOKE.XsSvInfo_m_qi_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_cno {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_cno_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsSvInfo_m_cno_get(swigCPtr);
      return ret;
    } 
  }

  public sbyte m_elev {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_elev_set(swigCPtr, value);
    } 
    get {
      sbyte ret = xsensdeviceapiPINVOKE.XsSvInfo_m_elev_get(swigCPtr);
      return ret;
    } 
  }

  public short m_azim {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_azim_set(swigCPtr, value);
    } 
    get {
      short ret = xsensdeviceapiPINVOKE.XsSvInfo_m_azim_get(swigCPtr);
      return ret;
    } 
  }

  public int m_prres {
    set {
      xsensdeviceapiPINVOKE.XsSvInfo_m_prres_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsSvInfo_m_prres_get(swigCPtr);
      return ret;
    } 
  }

  public XsSvInfo() : this(xsensdeviceapiPINVOKE.new_XsSvInfo(), true) {
  }

}

}
