//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsSyncPolarity {
  XSP_None = 0,
  XSP_RisingEdge = 1,
  XSP_PositivePulse = XSP_RisingEdge,
  XSP_FallingEdge = 2,
  XSP_NegativePulse = XSP_FallingEdge,
  XSP_Both
}

}
