
//  ==> COPYRIGHT (C) 2021 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE <==
//  WARNING: COPYRIGHT (C) 2021 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO AN END USER LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  
//  THIS SOFTWARE CAN CONTAIN OPEN SOURCE COMPONENTS WHICH CAN BE SUBJECT TO 
//  THE FOLLOWING GENERAL PUBLIC LICENSES:
//  ==> Qt GNU LGPL version 3: http://doc.qt.io/qt-5/lgpl.html <==
//  ==> LAPACK BSD License:  http://www.netlib.org/lapack/LICENSE.txt <==
//  ==> StackWalker 3-Clause BSD License: https://github.com/JochenKalmbach/StackWalker/blob/master/LICENSE <==
//  ==> Icon Creative Commons 3.0: https://creativecommons.org/licenses/by/3.0/legalcode <==
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsTimeInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsTimeInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsTimeInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsTimeInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsTimeInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint m_nano {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_nano_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_nano_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_year {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_year_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_year_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_month {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_month_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_month_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_day {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_day_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_day_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_hour {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_hour_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_hour_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_minute {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_minute_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_minute_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_second {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_second_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_second_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_valid {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_valid_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_valid_get(swigCPtr);
      return ret;
    } 
  }

  public short m_utcOffset {
    set {
      xsensdeviceapiPINVOKE.XsTimeInfo_m_utcOffset_set(swigCPtr, value);
    } 
    get {
      short ret = xsensdeviceapiPINVOKE.XsTimeInfo_m_utcOffset_get(swigCPtr);
      return ret;
    } 
  }

  public void clear() {
    xsensdeviceapiPINVOKE.XsTimeInfo_clear(swigCPtr);
  }

  public static XsTimeInfo currentTime() {
    XsTimeInfo ret = new XsTimeInfo(xsensdeviceapiPINVOKE.XsTimeInfo_currentTime(), true);
    return ret;
  }

  public static XsTimeInfo currentLocalTime() {
    XsTimeInfo ret = new XsTimeInfo(xsensdeviceapiPINVOKE.XsTimeInfo_currentLocalTime(), true);
    return ret;
  }

  public void makeUtc() {
    xsensdeviceapiPINVOKE.XsTimeInfo_makeUtc(swigCPtr);
  }

  public XsTimeInfo() : this(xsensdeviceapiPINVOKE.new_XsTimeInfo(), true) {
  }

}

}
