//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsComCallbackOptions {
  XSC_None = 0,
  XSC_LivePacket = 0x0001,
  XSC_LivePackets = 0x0002,
  XSC_RecordingPacket = 0x0004,
  XSC_RecordingPackets = 0x0008,
  XSC_All = 0x001F
}

}
