
//  ==> COPYRIGHT (C) 2021 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE <==
//  WARNING: COPYRIGHT (C) 2021 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO AN END USER LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  
//  THIS SOFTWARE CAN CONTAIN OPEN SOURCE COMPONENTS WHICH CAN BE SUBJECT TO 
//  THE FOLLOWING GENERAL PUBLIC LICENSES:
//  ==> Qt GNU LGPL version 3: http://doc.qt.io/qt-5/lgpl.html <==
//  ==> LAPACK BSD License:  http://www.netlib.org/lapack/LICENSE.txt <==
//  ==> StackWalker 3-Clause BSD License: https://github.com/JochenKalmbach/StackWalker/blob/master/LICENSE <==
//  ==> Icon Creative Commons 3.0: https://creativecommons.org/licenses/by/3.0/legalcode <==
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsDevicePtrArrayImpl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsDevicePtrArrayImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsDevicePtrArrayImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsDevicePtrArrayImpl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsDevicePtrArrayImpl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsDevicePtrArrayImpl(uint count, SWIGTYPE_p_p_XsDevice src) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArrayImpl__SWIG_0(count, SWIGTYPE_p_p_XsDevice.getCPtr(src)), true) {
  }

  public XsDevicePtrArrayImpl(uint count) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArrayImpl__SWIG_1(count), true) {
  }

  public XsDevicePtrArrayImpl() : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArrayImpl__SWIG_2(), true) {
  }

  public XsDevicePtrArrayImpl(SWIGTYPE_p_XsArrayImplT_XsDevicePtr_g_xsDevicePtrArrayDescriptor_XsDevicePtrArray_t__ArrayImpl other) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArrayImpl__SWIG_3(SWIGTYPE_p_XsArrayImplT_XsDevicePtr_g_xsDevicePtrArrayDescriptor_XsDevicePtrArray_t__ArrayImpl.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsDevicePtrArrayImpl(SWIGTYPE_p_p_XsDevice ref_, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArrayImpl__SWIG_4(SWIGTYPE_p_p_XsDevice.getCPtr(ref_), sz, (int)flags), true) {
  }

  public void clear() {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_clear(swigCPtr);
  }

  public void reserve(uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_reserve(swigCPtr, count);
  }

  public uint reserved() {
    uint ret = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_reserved(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_XsArrayDescriptor descriptor() {
    SWIGTYPE_p_XsArrayDescriptor ret = new SWIGTYPE_p_XsArrayDescriptor(xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_descriptor(swigCPtr), false);
    return ret;
  }

  public XsDevice value(uint index) {
    global::System.IntPtr cPtr = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_value(swigCPtr, index);
    XsDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDevice(cPtr, false);
    return ret;
  }

  public XsDevice first() {
    global::System.IntPtr cPtr = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_first(swigCPtr);
    XsDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDevice(cPtr, false);
    return ret;
  }

  public XsDevice last() {
    global::System.IntPtr cPtr = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_last(swigCPtr);
    XsDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDevice(cPtr, false);
    return ret;
  }

  public XsDevice at(uint index) {
    global::System.IntPtr cPtr = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_at__SWIG_0(swigCPtr, index);
    XsDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDevice(cPtr, false);
    return ret;
  }

  public void insert(XsDevice item, uint index) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_insert__SWIG_0(swigCPtr, XsDevice.getCPtr(item), index);
  }

  public void insert(SWIGTYPE_p_p_XsDevice items, uint index, uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_insert__SWIG_1(swigCPtr, SWIGTYPE_p_p_XsDevice.getCPtr(items), index, count);
  }

  public void push_back(XsDevice item) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_push_back(swigCPtr, XsDevice.getCPtr(item));
  }

  public void pop_back(uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_pop_back__SWIG_0(swigCPtr, count);
  }

  public void pop_back() {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_pop_back__SWIG_1(swigCPtr);
  }

  public void push_front(XsDevice item) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_push_front(swigCPtr, XsDevice.getCPtr(item));
  }

  public void pop_front(uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_pop_front__SWIG_0(swigCPtr, count);
  }

  public void pop_front() {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_pop_front__SWIG_1(swigCPtr);
  }

  public uint size() {
    uint ret = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_size(swigCPtr);
    return ret;
  }

  public void erase(uint index, uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_erase__SWIG_0(swigCPtr, index, count);
  }

  public void erase(uint index) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_erase__SWIG_1(swigCPtr, index);
  }

  public void assign(uint count, SWIGTYPE_p_p_XsDevice src) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_assign(swigCPtr, count, SWIGTYPE_p_p_XsDevice.getCPtr(src));
  }

  public void resize(uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_resize(swigCPtr, count);
  }

  public void setSize(uint count) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_setSize(swigCPtr, count);
  }

  public void append(SWIGTYPE_p_XsArrayImplT_XsDevicePtr_g_xsDevicePtrArrayDescriptor_XsDevicePtrArray_t__ArrayImpl other) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_append(swigCPtr, SWIGTYPE_p_XsArrayImplT_XsDevicePtr_g_xsDevicePtrArrayDescriptor_XsDevicePtrArray_t__ArrayImpl.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_empty(swigCPtr);
    return ret;
  }

  public void swap(SWIGTYPE_p_XsArrayImplT_XsDevicePtr_g_xsDevicePtrArrayDescriptor_XsDevicePtrArray_t__ArrayImpl other) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_swap__SWIG_0(swigCPtr, SWIGTYPE_p_XsArrayImplT_XsDevicePtr_g_xsDevicePtrArrayDescriptor_XsDevicePtrArray_t__ArrayImpl.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(uint a, uint b) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_swap__SWIG_1(swigCPtr, a, b);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsDevice needle) {
    SWIGTYPE_p_ptrdiff_t ret = new SWIGTYPE_p_ptrdiff_t(xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_find(swigCPtr, XsDevice.getCPtr(needle)), true);
    return ret;
  }

  public void removeDuplicates() {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_removeDuplicates(swigCPtr);
  }

  public void removeDuplicatesPredicate(SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int predicate) {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_removeDuplicatesPredicate(swigCPtr, SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int.getCPtr(predicate));
  }

  public void sort() {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_sort(swigCPtr);
  }

  public void reverse() {
    xsensdeviceapiPINVOKE.XsDevicePtrArrayImpl_reverse(swigCPtr);
  }

}

}
