//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsDeviceState {
  XDS_Initial,
  XDS_Config,
  XDS_Measurement,
  XDS_WaitingForRecordingStart,
  XDS_Recording,
  XDS_FlushingData,
  XDS_Destructing
}

}
