//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsDeviceIdArrayImpl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsDeviceIdArrayImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsDeviceIdArrayImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsDeviceIdArrayImpl() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsDeviceIdArrayImpl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsDeviceIdArrayImpl(uint count, XsDeviceId src) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArrayImpl__SWIG_0(count, XsDeviceId.getCPtr(src)), true) {
  }

  public XsDeviceIdArrayImpl(uint count) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArrayImpl__SWIG_1(count), true) {
  }

  public XsDeviceIdArrayImpl() : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArrayImpl__SWIG_2(), true) {
  }

  public XsDeviceIdArrayImpl(XsDeviceIdArrayImpl other) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArrayImpl__SWIG_3(XsDeviceIdArrayImpl.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsDeviceIdArrayImpl(XsDeviceId arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArrayImpl__SWIG_4(XsDeviceId.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsDeviceIdArrayImpl(XsDeviceId arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArrayImpl__SWIG_5(XsDeviceId.getCPtr(arg0), sz), true) {
  }

  public void clear() {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_clear(swigCPtr);
  }

  public void reserve(uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_reserve(swigCPtr, count);
  }

  public uint reserved() {
    uint ret = xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_reserved(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_XsArrayDescriptor descriptor() {
    SWIGTYPE_p_XsArrayDescriptor ret = new SWIGTYPE_p_XsArrayDescriptor(xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_descriptor(swigCPtr), false);
    return ret;
  }

  public XsDeviceId value(uint index) {
    XsDeviceId ret = new XsDeviceId(xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_value(swigCPtr, index), true);
    return ret;
  }

  public XsDeviceId at(uint index) {
    XsDeviceId ret = new XsDeviceId(xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_at__SWIG_0(swigCPtr, index), false);
    return ret;
  }

  public void insert(XsDeviceId item, uint index) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_insert__SWIG_0(swigCPtr, XsDeviceId.getCPtr(item), index);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void insert(XsDeviceId items, uint index, uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_insert__SWIG_1(swigCPtr, XsDeviceId.getCPtr(items), index, count);
  }

  public void push_back(XsDeviceId item) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_push_back(swigCPtr, XsDeviceId.getCPtr(item));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back(uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_pop_back__SWIG_0(swigCPtr, count);
  }

  public void pop_back() {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_pop_back__SWIG_1(swigCPtr);
  }

  public void push_front(XsDeviceId item) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_push_front(swigCPtr, XsDeviceId.getCPtr(item));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_front(uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_pop_front__SWIG_0(swigCPtr, count);
  }

  public void pop_front() {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_pop_front__SWIG_1(swigCPtr);
  }

  public uint size() {
    uint ret = xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_size(swigCPtr);
    return ret;
  }

  public void erase(uint index, uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_erase__SWIG_0(swigCPtr, index, count);
  }

  public void erase(uint index) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_erase__SWIG_1(swigCPtr, index);
  }

  public void assign(uint count, XsDeviceId src) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_assign(swigCPtr, count, XsDeviceId.getCPtr(src));
  }

  public void resize(uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_resize(swigCPtr, count);
  }

  public void setSize(uint count) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_setSize(swigCPtr, count);
  }

  public void append(XsDeviceIdArrayImpl other) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_append(swigCPtr, XsDeviceIdArrayImpl.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_empty(swigCPtr);
    return ret;
  }

  public void swap(XsDeviceIdArrayImpl other) {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_swap(swigCPtr, XsDeviceIdArrayImpl.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public int find(XsDeviceId needle) {
    int ret = xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_find(swigCPtr, XsDeviceId.getCPtr(needle));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void removeDuplicates() {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_removeDuplicates(swigCPtr);
  }

  public void sort() {
    xsensdeviceapiPINVOKE.XsDeviceIdArrayImpl_sort(swigCPtr);
  }

}

}
