//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsGpsPvtData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsGpsPvtData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsGpsPvtData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsGpsPvtData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsGpsPvtData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ushort m_pressure {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_pressure_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_pressure_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_pressureAge {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_pressureAge_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_pressureAge_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_itow {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_itow_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_itow_get(swigCPtr);
      return ret;
    } 
  }

  public int m_latitude {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_latitude_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_latitude_get(swigCPtr);
      return ret;
    } 
  }

  public int m_longitude {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_longitude_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_longitude_get(swigCPtr);
      return ret;
    } 
  }

  public int m_height {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_height_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_height_get(swigCPtr);
      return ret;
    } 
  }

  public int m_veln {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_veln_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_veln_get(swigCPtr);
      return ret;
    } 
  }

  public int m_vele {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_vele_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_vele_get(swigCPtr);
      return ret;
    } 
  }

  public int m_veld {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_veld_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_veld_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_hacc {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_hacc_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_hacc_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_vacc {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_vacc_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_vacc_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_sacc {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_sacc_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_sacc_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_gpsAge {
    set {
      xsensdeviceapiPINVOKE.XsGpsPvtData_m_gpsAge_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsGpsPvtData_m_gpsAge_get(swigCPtr);
      return ret;
    } 
  }

  public void clear() {
    xsensdeviceapiPINVOKE.XsGpsPvtData_clear(swigCPtr);
  }

  public bool empty() {
    bool ret = xsensdeviceapiPINVOKE.XsGpsPvtData_empty(swigCPtr);
    return ret;
  }

  public XsGpsPvtData() : this(xsensdeviceapiPINVOKE.new_XsGpsPvtData(), true) {
  }

}

}
