//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsRawGpsDop : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsRawGpsDop(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsRawGpsDop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsRawGpsDop() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsRawGpsDop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint m_itow {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_itow_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_itow_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_gdop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_gdop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_gdop_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_pdop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_pdop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_pdop_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_tdop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_tdop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_tdop_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_vdop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_vdop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_vdop_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_hdop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_hdop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_hdop_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_ndop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_ndop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_ndop_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_edop {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsDop_m_edop_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsDop_m_edop_get(swigCPtr);
      return ret;
    } 
  }

  public XsRawGpsDop() : this(xsensdeviceapiPINVOKE.new_XsRawGpsDop(), true) {
  }

}

}
