//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsRejectReason {
  XRR_Unknown = 0,
  XRR_VersionMismatch = 1,
  XRR_Blacklisted = 2,
  XRR_StationIsDisconnecting = 3,
  XRR_SystemIsOperational = 4
}

}
