
//  ==> COPYRIGHT (C) 2021 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE <==
//  WARNING: COPYRIGHT (C) 2021 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO AN END USER LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  
//  THIS SOFTWARE CAN CONTAIN OPEN SOURCE COMPONENTS WHICH CAN BE SUBJECT TO 
//  THE FOLLOWING GENERAL PUBLIC LICENSES:
//  ==> Qt GNU LGPL version 3: http://doc.qt.io/qt-5/lgpl.html <==
//  ==> LAPACK BSD License:  http://www.netlib.org/lapack/LICENSE.txt <==
//  ==> StackWalker 3-Clause BSD License: https://github.com/JochenKalmbach/StackWalker/blob/master/LICENSE <==
//  ==> Icon Creative Commons 3.0: https://creativecommons.org/licenses/by/3.0/legalcode <==
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsSelfTestResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsSelfTestResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsSelfTestResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsSelfTestResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsSelfTestResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ushort m_flags {
    set {
      xsensdeviceapiPINVOKE.XsSelfTestResult_m_flags_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsSelfTestResult_m_flags_get(swigCPtr);
      return ret;
    } 
  }

  public static XsSelfTestResult create(ushort resultFlags) {
    XsSelfTestResult ret = new XsSelfTestResult(xsensdeviceapiPINVOKE.XsSelfTestResult_create(resultFlags), true);
    return ret;
  }

  public bool accX() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_accX(swigCPtr);
    return ret;
  }

  public bool accY() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_accY(swigCPtr);
    return ret;
  }

  public bool accZ() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_accZ(swigCPtr);
    return ret;
  }

  public bool gyrX() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_gyrX(swigCPtr);
    return ret;
  }

  public bool gyrY() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_gyrY(swigCPtr);
    return ret;
  }

  public bool gyrZ() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_gyrZ(swigCPtr);
    return ret;
  }

  public bool magX() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_magX(swigCPtr);
    return ret;
  }

  public bool magY() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_magY(swigCPtr);
    return ret;
  }

  public bool magZ() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_magZ(swigCPtr);
    return ret;
  }

  public bool baro() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_baro(swigCPtr);
    return ret;
  }

  public bool gnss() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_gnss(swigCPtr);
    return ret;
  }

  public bool battery() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_battery(swigCPtr);
    return ret;
  }

  public bool flash() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_flash(swigCPtr);
    return ret;
  }

  public bool button() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_button(swigCPtr);
    return ret;
  }

  public bool sync() {
    bool ret = xsensdeviceapiPINVOKE.XsSelfTestResult_sync(swigCPtr);
    return ret;
  }

  public XsSelfTestResult() : this(xsensdeviceapiPINVOKE.new_XsSelfTestResult(), true) {
  }

}

}
