//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsStringArray : XsStringArrayImpl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal XsStringArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsStringArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsStringArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsStringArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsStringArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsStringArray(uint sz, XsString src) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_0(sz, XsString.getCPtr(src)), true) {
  }

  public XsStringArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_1(sz), true) {
  }

  public XsStringArray() : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_2(), true) {
  }

  public XsStringArray(XsStringArray other) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_3(XsStringArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsStringArray(XsString arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_4(XsString.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsStringArray(XsString arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_5(XsString.getCPtr(arg0), sz), true) {
  }

  public XsString join(XsString separator) {
    XsString ret = new XsString(xsensdeviceapiPINVOKE.XsStringArray_join(swigCPtr, XsString.getCPtr(separator)), true);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void fromSplicedString(XsString src, XsString separators) {
    xsensdeviceapiPINVOKE.XsStringArray_fromSplicedString(swigCPtr, XsString.getCPtr(src), XsString.getCPtr(separators));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
