//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsSyncSettingArrayImpl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsSyncSettingArrayImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsSyncSettingArrayImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsSyncSettingArrayImpl() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsSyncSettingArrayImpl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsSyncSettingArrayImpl(uint count, XsSyncSetting src) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArrayImpl__SWIG_0(count, XsSyncSetting.getCPtr(src)), true) {
  }

  public XsSyncSettingArrayImpl(uint count) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArrayImpl__SWIG_1(count), true) {
  }

  public XsSyncSettingArrayImpl() : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArrayImpl__SWIG_2(), true) {
  }

  public XsSyncSettingArrayImpl(XsSyncSettingArrayImpl other) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArrayImpl__SWIG_3(XsSyncSettingArrayImpl.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsSyncSettingArrayImpl(XsSyncSetting arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArrayImpl__SWIG_4(XsSyncSetting.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsSyncSettingArrayImpl(XsSyncSetting arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArrayImpl__SWIG_5(XsSyncSetting.getCPtr(arg0), sz), true) {
  }

  public void clear() {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_clear(swigCPtr);
  }

  public void reserve(uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_reserve(swigCPtr, count);
  }

  public uint reserved() {
    uint ret = xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_reserved(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_XsArrayDescriptor descriptor() {
    SWIGTYPE_p_XsArrayDescriptor ret = new SWIGTYPE_p_XsArrayDescriptor(xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_descriptor(swigCPtr), false);
    return ret;
  }

  public XsSyncSetting value(uint index) {
    XsSyncSetting ret = new XsSyncSetting(xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_value(swigCPtr, index), true);
    return ret;
  }

  public XsSyncSetting at(uint index) {
    XsSyncSetting ret = new XsSyncSetting(xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_at__SWIG_0(swigCPtr, index), false);
    return ret;
  }

  public void insert(XsSyncSetting item, uint index) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_insert__SWIG_0(swigCPtr, XsSyncSetting.getCPtr(item), index);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void insert(XsSyncSetting items, uint index, uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_insert__SWIG_1(swigCPtr, XsSyncSetting.getCPtr(items), index, count);
  }

  public void push_back(XsSyncSetting item) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_push_back(swigCPtr, XsSyncSetting.getCPtr(item));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back(uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_pop_back__SWIG_0(swigCPtr, count);
  }

  public void pop_back() {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_pop_back__SWIG_1(swigCPtr);
  }

  public void push_front(XsSyncSetting item) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_push_front(swigCPtr, XsSyncSetting.getCPtr(item));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_front(uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_pop_front__SWIG_0(swigCPtr, count);
  }

  public void pop_front() {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_pop_front__SWIG_1(swigCPtr);
  }

  public uint size() {
    uint ret = xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_size(swigCPtr);
    return ret;
  }

  public void erase(uint index, uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_erase__SWIG_0(swigCPtr, index, count);
  }

  public void erase(uint index) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_erase__SWIG_1(swigCPtr, index);
  }

  public void assign(uint count, XsSyncSetting src) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_assign(swigCPtr, count, XsSyncSetting.getCPtr(src));
  }

  public void resize(uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_resize(swigCPtr, count);
  }

  public void setSize(uint count) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_setSize(swigCPtr, count);
  }

  public void append(XsSyncSettingArrayImpl other) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_append(swigCPtr, XsSyncSettingArrayImpl.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_empty(swigCPtr);
    return ret;
  }

  public void swap(XsSyncSettingArrayImpl other) {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_swap(swigCPtr, XsSyncSettingArrayImpl.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public int find(XsSyncSetting needle) {
    int ret = xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_find(swigCPtr, XsSyncSetting.getCPtr(needle));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void removeDuplicates() {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_removeDuplicates(swigCPtr);
  }

  public void sort() {
    xsensdeviceapiPINVOKE.XsSyncSettingArrayImpl_sort(swigCPtr);
  }

}

}
