//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsUShortVector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsUShortVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsUShortVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsUShortVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsUShortVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsUShortVector() : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_0(), true) {
  }

  public XsUShortVector(ushort v1, ushort v2, ushort v3) : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_1(v1, v2, v3), true) {
  }

  public XsUShortVector(SWIGTYPE_p_unsigned_short a) : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_2(SWIGTYPE_p_unsigned_short.getCPtr(a)), true) {
  }

  public XsUShortVector(XsUShortVector other) : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_3(XsUShortVector.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint size() {
    uint ret = xsensdeviceapiPINVOKE.XsUShortVector_size(swigCPtr);
    return ret;
  }

  public ushort at(int index) {
    ushort ret = xsensdeviceapiPINVOKE.XsUShortVector_at(swigCPtr, index);
    return ret;
  }

  public SWIGTYPE_p_unsigned_short data() {
    global::System.IntPtr cPtr = xsensdeviceapiPINVOKE.XsUShortVector_data(swigCPtr);
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

}

}
