//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class XsUsbHubInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsUsbHubInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsUsbHubInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsUsbHubInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsUsbHubInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XsUsbHubInfo(int hubid) : this(xsensdeviceapiPINVOKE.new_XsUsbHubInfo__SWIG_0(hubid), true) {
  }

  public XsUsbHubInfo() : this(xsensdeviceapiPINVOKE.new_XsUsbHubInfo__SWIG_1(), true) {
  }

  public XsUsbHubInfo(XsUsbHubInfo other) : this(xsensdeviceapiPINVOKE.new_XsUsbHubInfo__SWIG_2(XsUsbHubInfo.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool parentPathMatches(XsUsbHubInfo other) {
    bool ret = xsensdeviceapiPINVOKE.XsUsbHubInfo_parentPathMatches(swigCPtr, XsUsbHubInfo.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isValid() {
    bool ret = xsensdeviceapiPINVOKE.XsUsbHubInfo_isValid(swigCPtr);
    return ret;
  }

  public int hub() {
    int ret = xsensdeviceapiPINVOKE.XsUsbHubInfo_hub(swigCPtr);
    return ret;
  }

}

}
